Fixed issue with buildout and Distribute.
Using $ python bootstrap.py -d
caused the following error.
While:
  Bootstrapping.
  Getting distribution for 'distribute'.
Error: Picked: distribute = 0.6.15

Looks like it is an interaction of buildout's
allow-picked-versions=false option and the fact that
Distribute impersonates setuptools.
Pin Distribute explicitly in versions.cfg